{"uuid": "9f011a4e-fda3-46b9-843b-1595279c258a", "children": ["7c67e50f-2ace-4905-954e-a93f42f6b56e"], "befores": [{"name": "driver", "status": "passed", "start": 1728662481737, "stop": 1728662483165}], "afters": [{"name": "driver::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: connect ECONNREFUSED 127.0.0.1:8100\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: connect ECONNREFUSED 127.0.0.1:8100\n    at JWProxy.command (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:350:13)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at XCUITestDriver.proxyCommand (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:103:35)\n    at XCUITestDriver.mobileTerminateApp (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/lib/commands/app-management.js:134:7)\n    at XCUITestDriver.executeMethod (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/execute.ts:36:12)\n    at XCUITestDriver.execute (/Users/kimkitae/.appium/node_modules/appium-xcuitest-driver/lib/commands/execute.js:118:14)\n", "trace": "  File \"/Users/kimkitae/.pyenv/versions/3.9.1/envs/assignment/lib/python3.9/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Users/kimkitae/.pyenv/versions/3.9.1/envs/assignment/lib/python3.9/site-packages/_pytest/fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/kimkitae/assignment/conftest.py\", line 32, in driver\n    execute_method.terminate_app()\n  File \"/Users/kimkitae/assignment/page/execute_method.py\", line 30, in terminate_app\n    self.driver.execute_script(\"mobile: terminateApp\", {\"bundleId\": \"com.aqx.prex\"})\n  File \"/Users/kimkitae/.pyenv/versions/3.9.1/envs/assignment/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 414, in execute_script\n    return self.execute(command, {\"script\": script, \"args\": converted_args})[\"value\"]\n  File \"/Users/kimkitae/.pyenv/versions/3.9.1/envs/assignment/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/kimkitae/.pyenv/versions/3.9.1/envs/assignment/lib/python3.9/site-packages/appium/webdriver/errorhandler.py\", line 125, in check_response\n    raise exception_class(msg=message, stacktrace=format_stacktrace(stacktrace))\n"}, "start": 1728662959345, "stop": 1728662959367}], "start": 1728662481737, "stop": 1728662959367}